version: '3'

services:
  web:
    build: .
    command: >
      sh -c " timeout 900 bash -c 'until (echo >/dev/tcp/mysql/3306) &>/dev/null; do sleep 1; done' && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_NAME=iberry
      - DATABASE_USER=iberry
      - DATABASE_PASSWORD=CzJ#euS88aXmOtz7W^&v
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306

  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: iberry
      MYSQL_USER: iberry
      MYSQL_PASSWORD: CzJ#euS88aXmOtz7W^&v
    volumes:
      - ./dumpfile.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "3306:3306"
